### ISSUE TITLE
Index doesn't get updated  

### ISSUE THREAD

**Issue by sh1ng** [h2oai/poboys_conda_package_server#3]
http://poboys.h2o.ai:6969/poboys/pkgs/linux-64 contains h2o4gpu-0.3.2, but not in http://poboys.h2o.ai:6969/poboys/pkgs/linux-64/index.html

From the index file it's seen something went wrong after `2019-04-11`

**Comment by hemenkapadia** [comment]
Hi @sh1ng - checking if this is a blocker in any way?

**Comment by sh1ng** [comment]
Besides a convenience to be be able to install with conda command, it's always possible download `bz2` conda pkg and install it locally. So no.

**Comment by hemenkapadia** [comment]
The docker container logs have the following, wondering if this is the reason

```
5/12/2020 9:44:59 AM172.17.2.150 - - [09/May/2020 02:36:19] "POST /poboys/upload HTTP/1.1" 303 0
5/12/2020 9:44:59 AM172.17.2.151 - - [11/May/2020 02:39:03] "POST /poboys/upload HTTP/1.1" 303 0
5/12/2020 9:44:59 AM172.17.0.250 - - [12/May/2020 16:28:28] "GET /poboys/pkgs/ HTTP/1.1" 404 748
5/12/2020 9:44:59 AM172.17.0.250 - - [12/May/2020 16:28:29] "GET /favicon.ico HTTP/1.1" 404 746
5/12/2020 9:44:59 AM172.17.0.250 - - [12/May/2020 16:28:45] "GET / HTTP/1.1" 200 2000
5/12/2020 9:44:59 AM172.17.0.250 - - [12/May/2020 16:29:05] "GET /poboys/pkgs HTTP/1.1" 200 986
5/12/2020 9:44:59 AM172.17.0.250 - - [12/May/2020 16:29:09] "GET /poboys/pkgs/noarch HTTP/1.1" 200 130582
5/12/2020 9:44:59 AM172.17.0.250 - - [12/May/2020 16:38:17] "GET /poboys/pkgs HTTP/1.1" 200 986
5/12/2020 9:44:59 AM172.17.0.250 - - [12/May/2020 16:38:30] "GET /poboys/pkgs HTTP/1.1" 200 986
5/12/2020 9:44:59 AM172.17.0.250 - - [12/May/2020 16:38:41] "GET /poboys/pkgs/linux-64 HTTP/1.1" 200 308035
5/12/2020 9:44:59 AM172.17.0.250 - - [12/May/2020 16:39:02] "GET /poboys/pkgs/noarch HTTP/1.1" 200 130582
5/12/2020 9:44:59 AM172.17.0.250 - - [12/May/2020 16:42:05] "GET /poboys/pkgs HTTP/1.1" 200 986
5/12/2020 9:44:59 AM172.17.0.250 - - [12/May/2020 16:42:06] "GET /poboys/pkgs/noarch HTTP/1.1" 200 130582
5/12/2020 9:44:59 AM172.17.0.250 - - [12/May/2020 16:43:28] "POST /poboys/anaconda/release/pkgs/noarch/h2oai_client-1.8.5-py36_54faf03_63.tar.bz2 HTTP/1.1" 303 0
5/12/2020 9:44:59 AM172.17.0.250 - - [12/May/2020 16:43:28] "GET /poboys/pkgs/noarch?message=VXNpbmcgQW5hY29uZGEgQVBJOiBodHRwczovL2FwaS5hbmFjb25kYS5vcmcKWW91IGFyZSBub3QgbG9nZ2VkIGluClVzaW5nIEFuYWNvbmRhIEFQSTogaHR0cHM6Ly9hcGkuYW5hY29uZGEub3JnCmgyb2FpJ3MgbG9naW4gc3VjY2Vzc2Z1bApVc2luZyBBbmFjb25kYSBBUEk6IGh0dHBzOi8vYXBpLmFuYWNvbmRhLm9yZwpVc2luZyAiaDJvYWkiIGFzIHVwbG9hZCB1c2VybmFtZQpEZXRlY3RpbmcgZmlsZSB0eXBlLi4uCkZpbGUgdHlwZSBpcyAiY29uZGEiCkV4dHJhY3RpbmcgY29uZGEgcGFja2FnZSBhdHRyaWJ1dGVzIGZvciB1cGxvYWQKQ3JlYXRpbmcgcGFja2FnZSAiaDJvYWlfY2xpZW50IgpDcmVhdGluZyByZWxlYXNlICIxLjguNSIKVXBsb2FkaW5nIGZpbGUgImgyb2FpL2gyb2FpX2NsaWVudC8xLjguNS9ub2FyY2gvaDJvYWlfY2xpZW50LTEuOC41LXB5MzZfNTRmYWYwM182My50YXIuYnoyIgpVcGxvYWQgY29tcGxldGUKY29uZGEgcGFja2FnZSBsb2NhdGVkIGF0OgpodHRwczovL2FuYWNvbmRhLm9yZy9oMm9haS9oMm9haV9jbGllbnQKClVzaW5nIEFuYWNvbmRhIEFQSTogaHR0cHM6Ly9hcGkuYW5hY29uZGEub3JnCmxvZ291dCBzdWNjZXNzZnVsCg== HTTP/1.1" 200 131320
5/12/2020 9:44:59 AM172.17.0.250 - - [12/May/2020 16:44:59] "POST /poboys/anaconda/release/pkgs/noarch/h2oai_client-1.8.5.1-py36_754403b_64.tar.bz2 HTTP/1.1" 303 0
5/12/2020 9:44:59 AM172.17.0.250 - - [12/May/2020 16:44:59] "GET /poboys/pkgs/noarch?message=VXNpbmcgQW5hY29uZGEgQVBJOiBodHRwczovL2FwaS5hbmFjb25kYS5vcmcKWW91IGFyZSBub3QgbG9nZ2VkIGluClVzaW5nIEFuYWNvbmRhIEFQSTogaHR0cHM6Ly9hcGkuYW5hY29uZGEub3JnCmgyb2FpJ3MgbG9naW4gc3VjY2Vzc2Z1bApVc2luZyBBbmFjb25kYSBBUEk6IGh0dHBzOi8vYXBpLmFuYWNvbmRhLm9yZwpVc2luZyAiaDJvYWkiIGFzIHVwbG9hZCB1c2VybmFtZQpEZXRlY3RpbmcgZmlsZSB0eXBlLi4uCkZpbGUgdHlwZSBpcyAiY29uZGEiCkV4dHJhY3RpbmcgY29uZGEgcGFja2FnZSBhdHRyaWJ1dGVzIGZvciB1cGxvYWQKQ3JlYXRpbmcgcGFja2FnZSAiaDJvYWlfY2xpZW50IgpDcmVhdGluZyByZWxlYXNlICIxLjguNS4xIgpVcGxvYWRpbmcgZmlsZSAiaDJvYWkvaDJvYWlfY2xpZW50LzEuOC41LjEvbm9hcmNoL2gyb2FpX2NsaWVudC0xLjguNS4xLXB5MzZfNzU0NDAzYl82NC50YXIuYnoyIgpVcGxvYWQgY29tcGxldGUKY29uZGEgcGFja2FnZSBsb2NhdGVkIGF0OgpodHRwczovL2FuYWNvbmRhLm9yZy9oMm9haS9oMm9haV9jbGllbnQKClVzaW5nIEFuYWNvbmRhIEFQSTogaHR0cHM6Ly9hcGkuYW5hY29uZGEub3JnCmxvZ291dCBzdWNjZXNzZnVsCg== HTTP/1.1" 200 131326
5/12/2020 1:50:54 PMDEBUG:conda_build.index:found 457 conda packages
5/12/2020 1:50:55 PMDEBUG:conda_build.index:loading index cache /opt/poboys_conda_package_server/pkgs/linux-64/.cache/index/h2o4gpu-cuda9-0.3.0.10000-py36_linux_64_17ff1f1_104.tar.bz2.json
5/12/2020 1:50:56 PMDEBUG:conda_build.index:hashing, extracting, and caching /opt/poboys_conda_package_server/pkgs/linux-64/h2o4gpu-cuda10-0.3.1.10000-py36_linux_64_838e6a6_9.tar.bz2
5/12/2020 1:54:40 PMDEBUG:conda_build.index:/opt/poboys_conda_package_server/pkgs/linux-64/h2o4gpu-cuda10-0.3.2-py36_linux_64_14204b2_14.tar.bz2 has no file info/run_exports.yaml
5/12/2020 2:07:59 PMActivating conda env...
5/12/2020 2:07:59 PMServing...
5/12/2020 2:08:00 PMDEBUG:conda_build.index:found 457 conda packages
5/12/2020 2:08:00 PMDEBUG:conda_build.index:loading index cache /opt/poboys_conda_package_server/pkgs/linux-64/.cache/index/h2o4gpu-cuda9-0.3.0.10000-py36_linux_64_17ff1f1_104.tar.bz2.json
5/12/2020 2:08:01 PMDEBUG:conda_build.index:hashing, extracting, and caching /opt/poboys_conda_package_server/pkgs/linux-64/h2o4gpu-cuda10-0.3.1.10000-py36_linux_64_838e6a6_9.tar.bz2
5/12/2020 2:09:23 PMDEBUG:conda_build.index:/opt/poboys_conda_package_server/pkgs/linux-64/h2o4gpu-cuda10-0.3.2-py36_linux_64_14204b2_14.tar.bz2 has no file info/run_exports.yaml
5/12/2020 2:14:53 PMActivating conda env...
5/12/2020 2:14:54 PMServing...
5/12/2020 2:14:55 PMDEBUG:conda_build.index:found 457 conda packages
5/12/2020 2:14:55 PMDEBUG:conda_build.index:loading index cache /opt/poboys_conda_package_server/pkgs/linux-64/.cache/index/h2o4gpu-cuda9-0.3.0.10000-py36_linux_64_17ff1f1_104.tar.bz2.json
5/12/2020 2:14:55 PMDEBUG:conda_build.index:hashing, extracting, and caching /opt/poboys_conda_package_server/pkgs/linux-64/h2o4gpu-cuda10-0.3.1.10000-py36_linux_64_838e6a6_9.tar.bz2
5/12/2020 2:16:32 PMDEBUG:conda_build.index:/opt/poboys_conda_package_server/pkgs/linux-64/h2o4gpu-cuda10-0.3.2-py36_linux_64_14204b2_14.tar.bz2 has no file info/run_exports.yaml
5/12/2020 2:46:55 PMTraceback (most recent call last):
5/12/2020 2:46:55 PM  File "/opt/anaconda/bin/conda-index", line 11, in <module>
5/12/2020 2:46:55 PM    sys.exit(main())
5/12/2020 2:46:55 PM  File "/opt/anaconda/lib/python3.7/site-packages/conda_build/cli/main_index.py", line 66, in main
5/12/2020 2:46:55 PM    return execute(sys.argv[1:])
5/12/2020 2:46:55 PM  File "/opt/anaconda/lib/python3.7/site-packages/conda_build/cli/main_index.py", line 62, in execute
5/12/2020 2:46:55 PM    threads=args.threads, subdir=args.subdir, patch_generator=args.patch_generator)
5/12/2020 2:46:55 PM  File "/opt/anaconda/lib/python3.7/site-packages/conda_build/api.py", line 386, in update_index
5/12/2020 2:46:55 PM    update_index(path, check_md5=check_md5, channel_name=channel_name, patch_generator=patch_generator, threads=threads)
5/12/2020 2:46:55 PM  File "/opt/anaconda/lib/python3.7/site-packages/conda_build/index.py", line 251, in update_index
5/12/2020 2:46:55 PM    return ChannelIndex(dir_path, channel_name, deep_integrity_check=check_md5, threads=threads).index(patch_generator=patch_generator, verbose=verbose)
5/12/2020 2:46:55 PM  File "/opt/anaconda/lib/python3.7/site-packages/conda_build/index.py", line 744, in index
5/12/2020 2:46:55 PM    repodata_from_packages[subdir] = self.index_subdir(subdir)
5/12/2020 2:46:55 PM  File "/opt/anaconda/lib/python3.7/site-packages/conda_build/index.py", line 864, in index_subdir
5/12/2020 2:46:55 PM    fn, mtime, size, index_json = future.result()
5/12/2020 2:46:55 PM  File "/opt/anaconda/lib/python3.7/concurrent/futures/_base.py", line 425, in result
5/12/2020 2:46:55 PM    return self.__get_result()
5/12/2020 2:46:55 PM  File "/opt/anaconda/lib/python3.7/concurrent/futures/_base.py", line 384, in __get_result
5/12/2020 2:46:55 PM    raise self._exception
5/12/2020 2:46:55 PM  File "/opt/anaconda/lib/python3.7/concurrent/futures/thread.py", line 57, in run
5/12/2020 2:46:55 PM    result = self.fn(*self.args, **self.kwargs)
5/12/2020 2:46:55 PM  File "/opt/anaconda/lib/python3.7/site-packages/conda_build/index.py", line 925, in _extract_to_cache
5/12/2020 2:46:55 PM    binary_index_json = tf.extractfile('info/index.json').read()
5/12/2020 2:46:55 PM  File "/opt/anaconda/lib/python3.7/tarfile.py", line 2066, in extractfile
5/12/2020 2:46:55 PM    tarinfo = self.getmember(member)
5/12/2020 2:46:55 PM  File "/opt/anaconda/lib/python3.7/tarfile.py", line 1750, in getmember
5/12/2020 2:46:55 PM    tarinfo = self._getmember(name)
5/12/2020 2:46:55 PM  File "/opt/anaconda/lib/python3.7/tarfile.py", line 2325, in _getmember
5/12/2020 2:46:55 PM    members = self.getmembers()
5/12/2020 2:46:55 PM  File "/opt/anaconda/lib/python3.7/tarfile.py", line 1761, in getmembers
5/12/2020 2:46:55 PM    self._load()        # all members, we first have to
5/12/2020 2:46:55 PM  File "/opt/anaconda/lib/python3.7/tarfile.py", line 2348, in _load
5/12/2020 2:46:55 PM    tarinfo = self.next()
5/12/2020 2:46:55 PM  File "/opt/anaconda/lib/python3.7/tarfile.py", line 2279, in next
5/12/2020 2:46:55 PM    self.fileobj.seek(self.offset - 1)
5/12/2020 2:46:55 PM  File "/opt/anaconda/lib/python3.7/bz2.py", line 274, in seek
5/12/2020 2:46:55 PM    return self._buffer.seek(offset, whence)
5/12/2020 2:46:55 PM  File "/opt/anaconda/lib/python3.7/_compression.py", line 143, in seek
5/12/2020 2:46:55 PM    data = self.read(min(io.DEFAULT_BUFFER_SIZE, offset))
5/12/2020 2:46:55 PM  File "/opt/anaconda/lib/python3.7/_compression.py", line 99, in read
5/12/2020 2:46:55 PM    raise EOFError("Compressed file ended before the "
5/12/2020 2:46:55 PMEOFError: Compressed file ended before the end-of-stream marker was reached
5/12/2020 2:46:55 PM2020-05-12 21:46:55,119 Serving on port 6969
```

**Comment by hemenkapadia** [comment]
Completed with the recent update of base and poboys container images.
